# {{ with secret "apps/data/springboot/dev/postgres" }}
app.postgres.host={{ .Data.data.host }}
app.postgres.port={{ .Data.data.port }}
app.postgres.database={{ .Data.data.database }}
app.postgres.username={{ .Data.data.username }}
app.postgres.password={{ .Data.data.password }}
# {{ end }}
